# Generated by Django 5.0.6 on 2024-06-12 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menusitem_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menusitem',
            old_name='text',
            new_name='description',
        ),
        migrations.AddField(
            model_name='menusitem',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='menusitem',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.category'),
        ),
        migrations.AlterField(
            model_name='menusitem',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
